name: BigBrother
main: com.Jakeob.BigBrother.BigBrother
version: 1.0
api-version: 1.13
commands:
   bb:
      description: Gets list of Big Brother commands
      usage: Usage /<command>
permissions:
  bb.use:
    description: Gives access to all Big Brother commands